version: '3.9'

services:
    db:
        container_name: yellow_app_db
        build:
            context: .
            dockerfile: Dockerfile-db
        ports:
            - '3306:3306'
        volumes:
            - ./logs:/var/log/mysql
            - ./mysql.cnf:/etc/mysql/mysql.conf.d/mysql.cnf
        # command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 60s
            retries: 2
        networks:
            - yellow-net

    app:
        container_name: yellow_app
        build:
            context: .
            dockerfile: Dockerfile-app
        ports:
            - '8080:8080'
        environment:
            - MYSQL_DB=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        depends_on:
            db:
                condition: service_healthy
        networks:
            - yellow-net

networks:
    yellow-net: {}
